# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: counters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='counters.proto',
  package='servicestatus',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63ounters.proto\x12\rservicestatus\x1a\x1cgoogle/api/annotations.proto\"\x1f\n\nCounterReq\x12\x11\n\tclient_id\x18\x01 \x01(\t\"*\n\x0b\x43ounterResp\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x05\x32R\n\x06Status\x12H\n\x0bGetCounters\x12\x19.servicestatus.CounterReq\x1a\x1a.servicestatus.CounterResp\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_COUNTERREQ = _descriptor.Descriptor(
  name='CounterReq',
  full_name='servicestatus.CounterReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='servicestatus.CounterReq.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=94,
)


_COUNTERRESP = _descriptor.Descriptor(
  name='CounterResp',
  full_name='servicestatus.CounterResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='servicestatus.CounterResp.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counter', full_name='servicestatus.CounterResp.counter', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['CounterReq'] = _COUNTERREQ
DESCRIPTOR.message_types_by_name['CounterResp'] = _COUNTERRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CounterReq = _reflection.GeneratedProtocolMessageType('CounterReq', (_message.Message,), {
  'DESCRIPTOR' : _COUNTERREQ,
  '__module__' : 'counters_pb2'
  # @@protoc_insertion_point(class_scope:servicestatus.CounterReq)
  })
_sym_db.RegisterMessage(CounterReq)

CounterResp = _reflection.GeneratedProtocolMessageType('CounterResp', (_message.Message,), {
  'DESCRIPTOR' : _COUNTERRESP,
  '__module__' : 'counters_pb2'
  # @@protoc_insertion_point(class_scope:servicestatus.CounterResp)
  })
_sym_db.RegisterMessage(CounterResp)



_STATUS = _descriptor.ServiceDescriptor(
  name='Status',
  full_name='servicestatus.Status',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=140,
  serialized_end=222,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCounters',
    full_name='servicestatus.Status.GetCounters',
    index=0,
    containing_service=None,
    input_type=_COUNTERREQ,
    output_type=_COUNTERRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATUS)

DESCRIPTOR.services_by_name['Status'] = _STATUS

# @@protoc_insertion_point(module_scope)
